### ISSUE TITLE
Need option to forego the real-time displaying of plots

### ISSUE THREAD

**Issue by umranhaji** [UCBerkeleySETI/filterbank#1]
Add optional argument to deactivate the `plt.show()` at the end

**Comment by umranhaji** [comment]
Realized this is accomplished by the `-i` argument. Apologies.

**Comment by umranhaji** [comment]
Realized the `-i` argument prevents the saving of plots even in conjunction with the `-s`argument. So, this is still an issue after all.

**Comment by telegraphic** [comment]
ok, I've added -S (capital S) flag for save only. Give it a whirl and let me know if that's the functionality you need.

**Comment by umranhaji** [comment]
Thank you very much for this and the $DISPLAY fix; my shell wrapper now works seamlessly with your script!
