### ISSUE TITLE
setup requirements

### ISSUE THREAD

**Issue by griffinfoster** [UCBerkeleySETI/filterbank#14]
Could you please list the external module requirements and the preferred version/setup method?

They seem to be h5py, Cython, and bitshiffle. bitshuffle 0.2.4 via pip does not seem to compile on ubuntu.

**Comment by telegraphic** [comment]
Yes, bitshuffle is a pain to install on current Ubuntu as it's HDF5 setup is strange. Ideally h5py and Cython are optional dependencies

**Comment by telegraphic** [comment]
I've added cython and h5py to these to the setup.py as dependencies. bitshuffle imports are now wrapped in `try: except ImportError:` so should be optional. Closing this for now.
