### ISSUE TITLE
Importing filterbank breaks matplotlib throughout entire script

### ISSUE THREAD

**Issue by umranhaji** [UCBerkeleySETI/filterbank#5]
All of a sudden, using the latest version of `filterbank.py`, I am noticing that, when not using X-forwarding, importing the `filterbank` module (or a class or function therein) messes up the matplotlib backend, resulting in a $DISPLAY error.

(This may seem similar to a previous issue regarding $DISPLAY errors; note that the previous issue occured when `filterbank.py` was the main program, whereas this issue occurs when importing it as a module)

The problem occurs regardless of whether or not the `filterbank` module is actually used in one's script, and it occurs even if one attempts to forcibly set a `matplotlib` backend after importing `filterbank`.

To see what I mean, try running the following code on either the BL head node or storage node, without X-forwarding:

```
import filterbank
import random

import matplotlib
matplotlib.use('pdf') #forcibly defining the backend does not fix the problem
import matplotlib.pyplot as plt

x = random.sample(range(1,100), 10)
y = random.sample(range(1,100), 10)
plt.plot(x,y)
plt.savefig('myplot.pdf', format='pdf')
```

Even though the `filterbank` module is used nowhere in the script, the `import filterbank` line breaks matplotlib.

Comment out the `import filterbank` line and you will notice that the script works as expected.

Your help is greatly appreciated.

**Comment by telegraphic** [comment]
Can you try with this new script? I made a local edit and hadn't pushed it to github

**Comment by telegraphic** [comment]
PS: You're probably also seeing 

```
/usr/local/lib/python2.7/dist-packages/matplotlib/__init__.py:1350: UserWarning:  This call to matplotlib.use() has no effect
because the backend has already been chosen;
matplotlib.use() must be called *before* pylab, matplotlib.pyplot,
or matplotlib.backends is imported for the first time.
```

What is likely happening in your version is that matplotlib is necessarily loaded when you import `filterbank`. For example, this code work:

```python 
import filterbank
import random

x = random.sample(range(1,100), 10)
y = random.sample(range(1,100), 10)
filterbank.plt.plot(x,y)
filterbank.plt.savefig('myplot.pdf', format='pdf')
```

**Comment by umranhaji** [comment]
You are correct, I am seeing the `UserWarning` above. 

Anyways, I cloned the most recent version of `filterbank.py` and tried it; that seems to have fixed the problem and the plot is generated without issue, though the `UserWarning` persists. 😕
