### ISSUE TITLE
Why do Filterbank data arrays contain an empty dimension?

### ISSUE THREAD

**Issue by umranhaji** [UCBerkeleySETI/filterbank#8]
This is a very minor inconvenience but I have been wondering about it for a while: why is it that extracting the data array from a Filterbank object with `self.data` yields a numpy array containing an extra empty dimension?

For example, taking a file with 273 integrations and 65536 channels (typical values for files ending in '0002.fil'), turning it into a Filterbank object, and running `self.data` yields an array of shape (273, 1, 65536). Why the extra dimension instead of just being (273, 65536)?

I also notice that this does _not_ happen when using the `grab_data` function. Is there a particular reason for this?

**Comment by telegraphic** [comment]
Hey Umran, happy 2017.

IIRC the dimensions are (time, beam, channel). So for the Parkes Multibeam
receiver, this dimension would not be empty. *grab_data* probably collapses
this as it's pretty annoying (but this may not be ideal in the long run).

- Danny

**Comment by umranhaji** [comment]
Thanks for the explanation, Danny. Happy New Year to you too!
